defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 红心地瓜的窝

title: 有朋自远方来，不亦乐乎
description: 红心地瓜
url: "http://dlmu2001.github.io"

author:
  name: dlmu2001
  email: tomorrow_cyz@163.com 
  github: dlmu2001
  bio: keep calm and carry on!

categories_path: categories.html
tags_path: tags.html

BASE_PATH:

markdown: kramdown
